{% set version = "3.1.0b1" %}
{% set build_num = 0 %}
{% if use_noarch == "True" %}
{%   set build_num = build_num + 100 %}
{% endif %}
# linter doesn't know the values from the variants
{% if python_min is undefined %}
{% set python_min = "3.9" %}
{% endif %}

package:
  name: cython
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/f5/6a/b820fd8626fa6a658880815dc99dea8318438dabee96d75e261d050d94d8/cython-3.1.0b1.tar.gz
  sha256: 3bfddd63e8e46eeeddc8283f47c4a16a2e98263ca9f9b215fe6ddbb69a9a185f

build:
  number: {{ build_num }}
  noarch: python   # [use_noarch]
  # only build noarch packages on linux64...
  skip: true       # [use_noarch and not linux64]
  # ... and using python_min
  {% if py|string != python_min.replace(".", "") %}
  skip: true       # [use_noarch]
  {% endif %}
  script:
    - export NO_CYTHON_COMPILE=true                   # [use_noarch]
    - {{ PYTHON }} -m pip install . --no-deps -vv
  track_features:
    - cython_no_compile    # [use_noarch]
  entry_points:
    - cython = Cython.Compiler.Main:setuptools_main
    - cythonize = Cython.Build.Cythonize:main
    - cygdb = Cython.Debugger.Cygdb:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python {{ python_min }}.*     # [use_noarch]
    - python                        # [not use_noarch]
    - pip
    - setuptools
  run:
    - python >={{ python_min }}     # [use_noarch]
    - python                        # [not use_noarch]

test:
  requires:
    - setuptools                    # [use_noarch or py>=312]
    - python {{ python_min }}       # [use_noarch]
  commands:
    - cython --version
  files:
    - fib.pyx

about:
  home: http://www.cython.org/
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: The Cython compiler for writing C extensions for the Python language
  description: |
    Cython is an optimising static compiler for both the Python programming
    language and the extended Cython programming language. It makes writing C
    extensions for Python as easy as Python itself.
  doc_url: https://docs.cython.org
  dev_url: https://github.com/cython/cython

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - ocefpaf
    - synapticarbors
    - isuruf
    - scopatz
    - h-vetinari
