{% set version = "3.0a7" %}

package:
  name: cython
  version: {{ version }}

source:
  url: https://github.com/cython/cython/archive/refs/tags/{{ version }}.tar.gz
  sha256: a741452364c8b3e345936ae7e7a24444f4dee37c762db0f1520340ad0c0ede48

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - cython = Cython.Compiler.Main:setuptools_main
    - cythonize = Cython.Build.Cythonize:main
    - cygdb = Cython.Debugger.Cygdb:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python

test:
  # this section automatically executes run_test.py (from recipe)
  files:
    - fib.pyx      # needed by run_test.py
  source_files:
    - runtests.py  # from repo
  commands:
    - cython --version
    - python -vv -x Debugger runtests.py

about:
  home: http://www.cython.org/
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: The Cython compiler for writing C extensions for the Python language
  description: |
    Cython is an optimising static compiler for both the Python programming
    language and the extended Cython programming language. It makes writing C
    extensions for Python as easy as Python itself.
  doc_url: http://cython.org/#documentation
  dev_url: https://github.com/cython/cython

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - ocefpaf
    - synapticarbors
    - isuruf
    - scopatz
