{% set version = "3.0.0a10" %}

package:
  name: cython
  version: {{ version }}

source:
  url: https://github.com/cython/cython/archive/refs/tags/{{ version }}.tar.gz
  sha256: d530216e015fd365bf3327a176e0073d0e5b8d48781f387336459f10032d776f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - cython = Cython.Compiler.Main:setuptools_main
    - cythonize = Cython.Build.Cythonize:main
    - cygdb = Cython.Debugger.Cygdb:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python

test:
  # this section automatically executes run_test.py (from recipe)
  files:
    - fib.pyx      # needed by run_test.py
  source_files:
    - runtests.py  # from repo
    # files below needed by runtests.py
    - cython.py
    - tests/
    - Cython/Runtime/refnanny.pyx
    - Demos/embed
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - numpy
    - setuptools
  commands:
    - cython --version
    # prevent the C compiler from doing anything fancy that takes more time than the test run afterwards
    - export CFLAGS="$CFLAGS -Og"       # [unix]
    - set "CFLAGS=%CFLAGS% -Og"         # [win]
    - python runtests.py -j$CPU_COUNT   # [unix]
    - python runtests.py -j%CPU_COUNT%  # [win]

about:
  home: http://www.cython.org/
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: The Cython compiler for writing C extensions for the Python language
  description: |
    Cython is an optimising static compiler for both the Python programming
    language and the extended Cython programming language. It makes writing C
    extensions for Python as easy as Python itself.
  doc_url: http://cython.org/#documentation
  dev_url: https://github.com/cython/cython

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - ocefpaf
    - synapticarbors
    - isuruf
    - scopatz
