{% set version = "3.0.12" %}
{% set build_num = 0 %}
{% if use_noarch == "True" %}
{%   set build_num = build_num + 100 %}
{% endif %}

package:
  name: cython
  version: {{ version }}

source:
  url: https://github.com/cython/cython/archive/refs/tags/{{ version }}.tar.gz
  sha256: a156fff948c2013f2c8c398612c018e2b52314fdf0228af8fbdb5585e13699c2

build:
  number: {{ build_num }}
  skip: true       # [use_noarch and not linux64]
  noarch: python   # [use_noarch]
  script:
    - export NO_CYTHON_COMPILE=true                   # [use_noarch]
    - {{ PYTHON }} -m pip install . --no-deps -vv
  track_features:
    - cython_no_compile    # [use_noarch]
  entry_points:
    - cython = Cython.Compiler.Main:setuptools_main
    - cythonize = Cython.Build.Cythonize:main
    - cygdb = Cython.Debugger.Cygdb:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python {{ python_min }}    # [use_noarch]
    - python                     # [not use_noarch]
    - pip
    - setuptools
  run:
    - python >={{ python_min }}  # [use_noarch]
    - python                     # [not use_noarch]

test:
  requires:
    - python {{ python_min }}    # [use_noarch]
    - setuptools                 # [py>=312 or use_noarch]
  commands:
    - cython --version
  files:
    - fib.pyx

about:
  home: http://www.cython.org/
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: The Cython compiler for writing C extensions for the Python language
  description: |
    Cython is an optimising static compiler for both the Python programming
    language and the extended Cython programming language. It makes writing C
    extensions for Python as easy as Python itself.
  doc_url: https://docs.cython.org
  dev_url: https://github.com/cython/cython

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - ocefpaf
    - synapticarbors
    - isuruf
    - scopatz
    - h-vetinari
