{% set version = "3.0.0b1" %}

package:
  name: cython
  version: {{ version }}

source:
  url: https://github.com/cython/cython/archive/refs/tags/{{ version }}.tar.gz
  sha256: bca121dbe96c88de9f2369d9d9231dd6b481cca486514421ed8252b4390eab5b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - cython = Cython.Compiler.Main:setuptools_main
    - cythonize = Cython.Build.Cythonize:main
    - cygdb = Cython.Debugger.Cygdb:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python

test:
  # this section automatically executes run_test.py (from recipe)
  files:
    - fib.pyx      # needed by run_test.py
  source_files:
    - runtests.py  # from repo
    # files below needed by runtests.py
    - cython.py
    - tests/
    - Cython/Runtime/refnanny.pyx
    - Demos/embed
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - setuptools
    - numpy *
    - pythran
    - tbb-devel  # [linux]
    - make       # [linux]
  commands:
    - cython --version
    # prevent the C compiler from doing anything fancy that takes more time than the test run afterwards
    - export CFLAGS="$CFLAGS -Og"  # [unix]
    - set "CFLAGS=%CFLAGS% -Og"    # [win]
    - python runtests.py

about:
  home: http://www.cython.org/
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: The Cython compiler for writing C extensions for the Python language
  description: |
    Cython is an optimising static compiler for both the Python programming
    language and the extended Cython programming language. It makes writing C
    extensions for Python as easy as Python itself.
  doc_url: https://docs.cython.org
  dev_url: https://github.com/cython/cython

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - ocefpaf
    - synapticarbors
    - isuruf
    - scopatz
    - h-vetinari
