travis:
  secure:
    BINSTAR_TOKEN: kEvpPnTrKqHRVXg87cFLAN4JzFh42lCIJK6nJ262UqpguTEvfhBemtsfE9e19vsmC9cxyGMj015Y36iVFlwEVqxc+CdxwAA3bvxodAWtfeAQudbklJDHgqahtp27hxd928ORZuaNm6V8uOqBFBxMOKoQCGI9Jc9Vqb+oGIbJ9wUykxpGe3GjhXweuKg30gumGHoqvelizUSEQ17AxJQUmeYztGbe7VZoXYQG15DqRNM0d70cKDmndIx2Zz+39k9vpzdvSFnb3MW+o9QBxm1BElaLxgW2XqRMRVJMJZggqRrxDTKTlBWlWx8r+2zyMl6Gc9dQV0CLz2qFyvmSi0ii2LuFuXQsJeIkDC3ovmQElmfIOhnV2Yl6Q1IbcbytX2b1lN3yZ2y5EA71cNCxTZWpafv/3IdcK9E54IIlObQTgGvj6qh6wRBs3BPAWL5x4R4lQpK2ODzDGBgL4t7wi3ydO3ifvxcdwr4jll1JZcJER6agQU3P3r4sneiTG8yLnzMVZVf+RlbZUnrHHTKYg8dfRr4lPLBsK8TXjvGcSuhBCCx1q4B4PaNzXP0NbVPAtgC7TlEjBu24LA2tokb9Exkvj4RF3I4NhB/7QWAVeBc2eeBw2KTkF4ZsuyfXIFdlDL6wmme85GYOmvgEQU4QXYKSPc1t+q5dKQhxqIVG1Sr8Mhk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
