# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: win
  pool:
    vmImage: windows-2022
  strategy:
    matrix:
      win_64_python3.10.____cpythonuse_noarchFalse:
        CONFIG: win_64_python3.10.____cpythonuse_noarchFalse
        UPLOAD_PACKAGES: 'True'
<<<<<<< HEAD
      win_64_python3.11.____cpython:
        CONFIG: win_64_python3.11.____cpython
        UPLOAD_PACKAGES: 'True'
      win_64_python3.8.____73_pypy:
        CONFIG: win_64_python3.8.____73_pypy
=======
      win_64_python3.11.____cpythonuse_noarchFalse:
        CONFIG: win_64_python3.11.____cpythonuse_noarchFalse
        UPLOAD_PACKAGES: 'True'
      win_64_python3.12.____cpythonuse_noarchFalse:
        CONFIG: win_64_python3.12.____cpythonuse_noarchFalse
>>>>>>> 08ce916a453eeb3bf2932d0a658387c6fe48e413
        UPLOAD_PACKAGES: 'True'
      win_64_python3.13.____cp313use_noarchFalse:
        CONFIG: win_64_python3.13.____cp313use_noarchFalse
        UPLOAD_PACKAGES: 'True'
<<<<<<< HEAD
      win_64_python3.9.____73_pypy:
        CONFIG: win_64_python3.9.____73_pypy
        UPLOAD_PACKAGES: 'True'
      win_64_python3.9.____cpython:
        CONFIG: win_64_python3.9.____cpython
=======
      win_64_python3.9.____cpythonuse_noarchFalse:
        CONFIG: win_64_python3.9.____cpythonuse_noarchFalse
>>>>>>> 08ce916a453eeb3bf2932d0a658387c6fe48e413
        UPLOAD_PACKAGES: 'True'
  timeoutInMinutes: 360
  variables:
    CONDA_BLD_PATH: D:\\bld\\
    UPLOAD_TEMP: D:\\tmp

  steps:
<<<<<<< HEAD
=======

>>>>>>> 08ce916a453eeb3bf2932d0a658387c6fe48e413
    - task: PythonScript@0
      displayName: 'Download Miniforge'
      inputs:
        scriptSource: inline
        script: |
          import urllib.request
<<<<<<< HEAD
          url = 'https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Windows-x86_64.exe'
          path = r"$(Build.ArtifactStagingDirectory)/Miniforge.exe"
          urllib.request.urlretrieve(url, path)

    - script: |
        start /wait "" %BUILD_ARTIFACTSTAGINGDIRECTORY%\Miniforge.exe /InstallationType=JustMe /RegisterPython=0 /S /D=C:\Miniforge
      displayName: Install Miniforge

    - powershell: Write-Host "##vso[task.prependpath]C:\Miniforge\Scripts"
      displayName: Add conda to PATH

    - script: |
        call activate base
        mamba.exe install "python=3.10" conda-build conda pip boa conda-forge-ci-setup=3 -c conda-forge --strict-channel-priority --yes
      displayName: Install conda-build

    - script: set PYTHONUNBUFFERED=1
      displayName: Set PYTHONUNBUFFERED

    # Configure the VM
    - script: |
        call activate base
        setup_conda_rc .\ ".\recipe" .\.ci_support\%CONFIG%.yaml
      displayName: conda-forge CI setup

    # Configure the VM.
    - script: |
        set "CI=azure"
        call activate base
        run_conda_forge_build_setup
      displayName: conda-forge build setup

    - script: |
        call activate base
        if EXIST LICENSE.txt (
          copy LICENSE.txt "recipe\\recipe-scripts-license.txt"
        )
        if NOT [%HOST_PLATFORM%] == [%BUILD_PLATFORM%] (
          set "EXTRA_CB_OPTIONS=%EXTRA_CB_OPTIONS% --no-test"
        )
        conda.exe mambabuild "recipe" -m .ci_support\%CONFIG%.yaml --suppress-variables %EXTRA_CB_OPTIONS%
      displayName: Build recipe
      env:
        PYTHONUNBUFFERED: 1
    - script: |
        set "FEEDSTOCK_NAME=%BUILD_REPOSITORY_NAME:*/=%"
        call activate base
        validate_recipe_outputs "%FEEDSTOCK_NAME%"
      displayName: Validate Recipe Outputs

    - script: |
        set "GIT_BRANCH=%BUILD_SOURCEBRANCHNAME%"
        set "FEEDSTOCK_NAME=%BUILD_REPOSITORY_NAME:*/=%"
        set "TEMP=$(UPLOAD_TEMP)"
        if not exist "%TEMP%\" md "%TEMP%"
        set "TMP=%TEMP%"
        call activate base
        upload_package --validate --feedstock-name="%FEEDSTOCK_NAME%" .\ ".\recipe" .ci_support\%CONFIG%.yaml
      displayName: Upload package
      env:
=======
          url = 'https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Windows-x86_64.exe'
          path = r"$(Build.ArtifactStagingDirectory)/Miniforge.exe"
          urllib.request.urlretrieve(url, path)

    - script: |
        start /wait "" %BUILD_ARTIFACTSTAGINGDIRECTORY%\Miniforge.exe /InstallationType=JustMe /RegisterPython=0 /S /D=C:\Miniforge
      displayName: Install Miniforge

    - powershell: Write-Host "##vso[task.prependpath]C:\Miniforge\Scripts"
      displayName: Add conda to PATH

    - script: |
        call ".scripts\run_win_build.bat"
      displayName: Run Windows build
      env:
        PYTHONUNBUFFERED: 1
        CONFIG: $(CONFIG)
        CI: azure
        flow_run_id: azure_$(Build.BuildNumber).$(System.JobAttempt)
        remote_url: $(Build.Repository.Uri)
        sha: $(Build.SourceVersion)
        UPLOAD_PACKAGES: $(UPLOAD_PACKAGES)
        UPLOAD_TEMP: $(UPLOAD_TEMP)
>>>>>>> 08ce916a453eeb3bf2932d0a658387c6fe48e413
        BINSTAR_TOKEN: $(BINSTAR_TOKEN)
        FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
        STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)