# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: win
  pool:
    vmImage: windows-2022
  strategy:
    matrix:
      win_64_is_freethreadingfalseis_python_minfalsepython3.11.____cpythonuse_noarchFalse:
        CONFIG: win_64_is_freethreadingfalseis_python_minfalsepython3.11.____cpythonuse_noarchFalse
        UPLOAD_PACKAGES: 'True'
        build_workspace_dir: D:\\bld\\
        free_disk_space: skip
        pagefile_size: 0
        resize_partitions: false
        store_build_artifacts: false
        tools_install_dir: D:\Miniforge
      win_64_is_freethreadingfalseis_python_minfalsepython3.12.____cpythonuse_noarchFalse:
        CONFIG: win_64_is_freethreadingfalseis_python_minfalsepython3.12.____cpythonuse_noarchFalse
        UPLOAD_PACKAGES: 'True'
        build_workspace_dir: D:\\bld\\
        free_disk_space: skip
        pagefile_size: 0
        resize_partitions: false
        store_build_artifacts: false
        tools_install_dir: D:\Miniforge
      win_64_is_freethreadingfalseis_python_minfalsepython3.13.____cp313use_noarchFalse:
        CONFIG: win_64_is_freethreadingfalseis_python_minfalsepython3.13.____cp313use_noarchFalse
        UPLOAD_PACKAGES: 'True'
        build_workspace_dir: D:\\bld\\
        free_disk_space: skip
        pagefile_size: 0
        resize_partitions: false
        store_build_artifacts: false
        tools_install_dir: D:\Miniforge
      win_64_is_freethreadingfalseis_python_minfalsepython3.14.____cp314use_noarchFalse:
        CONFIG: win_64_is_freethreadingfalseis_python_minfalsepython3.14.____cp314use_noarchFalse
        UPLOAD_PACKAGES: 'True'
        build_workspace_dir: D:\\bld\\
        free_disk_space: skip
        pagefile_size: 0
        resize_partitions: false
        store_build_artifacts: false
        tools_install_dir: D:\Miniforge
      win_64_is_freethreadingfalseis_python_mintruepython3.10.____cpythonuse_noarchFalse:
        CONFIG: win_64_is_freethreadingfalseis_python_mintruepython3.10.____cpythonuse_noarchFalse
        UPLOAD_PACKAGES: 'True'
        build_workspace_dir: D:\\bld\\
        free_disk_space: skip
        pagefile_size: 0
        resize_partitions: false
        store_build_artifacts: false
        tools_install_dir: D:\Miniforge
      win_64_is_freethreadingtrueis_python_minfalsepython3.14.____cp314tuse_noarchFalse:
        CONFIG: win_64_is_freethreadingtrueis_python_minfalsepython3.14.____cp314tuse_noarchFalse
        UPLOAD_PACKAGES: 'True'
        build_workspace_dir: D:\\bld\\
        free_disk_space: skip
        pagefile_size: 0
        resize_partitions: false
        store_build_artifacts: false
        tools_install_dir: D:\Miniforge
  timeoutInMinutes: 360
  variables:
    UPLOAD_TEMP: D:\\tmp

  steps:
    - script: |
        call ".scripts\run_win_build.bat"
      displayName: Run Windows build
      env:
        CI: azure
        CONFIG: $(CONFIG)
        CONDA_BLD_PATH: $(build_workspace_dir)
        MINIFORGE_HOME: $(tools_install_dir)
        PYTHONUNBUFFERED: 1
        UPLOAD_PACKAGES: $(UPLOAD_PACKAGES)
        UPLOAD_TEMP: $(UPLOAD_TEMP)
        flow_run_id: azure_$(Build.BuildNumber).$(System.JobAttempt)
        remote_url: $(Build.Repository.Uri)
        sha: $(Build.SourceVersion)
        BINSTAR_TOKEN: $(BINSTAR_TOKEN)
        FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
        STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
